function dsp1
%DSP1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 31-Mar-2019 21:39:22

% FIR Window Bandpass filter 	 using the FIR1 function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N    = 38;       % Order
Fc1  = 10;       % First Cutoff Frequency
Fc2  = 20;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 3.4;      % Window Parameter
% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
